version: 2.1

jobs:
  build:
    machine:
      image: "ubuntu-2004:202010-01"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc-9 g++-9 gfortran-9'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Installing Third-Party Libraries      
          command: 'GNU_PARALLEL=OFF ./install-tpl.sh'
      - run:
          name: Configure
          command: 'mkdir build && cd build && ../cmake-config'
      - run:
          name: Build
          command: 'pwd && cmake --build build'
      - run:
          name: Test
          command: 'cd build && ctest -VV'

