name: test-clang-format

on: [push]

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - uses: DoozyX/clang-format-lint-action@v0.18.1
      with:
        source: 'packages/seacas'
        exclude: 'packages/seacas/doc-source'
        extensions: 'c,C,h,cpp'
        clangFormatVersion: 18
        style: file
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Clang-Format Robot
        author_email: gsjaardema@gmail.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}