name: docker
on:
  push:
    branches: [ "master" ]
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v2.8.0
        with:
          context: docker/seacas
          push: true
          tags: mrbuche/seacas:latest
      - name: Delay before pull
        run: sleep 234s
  test-latest:
    needs: build-latest
    runs-on: ubuntu-latest
    container: mrbuche/seacas
    steps:
      - name: Docker pull and test
        run: |
          cd /seacas/build/ && ctest --output-on-failure && cd
          cd /seacas/SEACAS-Test/ && make test && cd
          python -c 'import exodus3 as exodus'
  build-exodus-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v2.8.0
        with:
          context: docker/exodus
          push: true
          tags: mrbuche/exodus:latest
      - name: Delay before pull
        run: sleep 234s
  test-exodus-latest:
    needs: build-exodus-latest
    runs-on: ubuntu-latest
    container: mrbuche/exodus
    steps:
      - name: Docker pull and test
        run: |
          python -c 'import exodus3 as exodus'
