name: SEACAS MSYS2 Build
on: 
  push:
    branches-ignore:
      - 'coverity'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain automake libtool autoconf make mingw-w64-x86_64-hdf5 mingw-w64-x86_64-cgns mingw-w64-x86_64-netcdf mingw-w64-x86_64-zlib
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-msys2-build.sh
