name: Python Linting
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pylint
      - name: Lint with flake8
        run: |
          flake8 packages/seacas/scripts/exodus3.in.py --count --show-source --statistics
          flake8 packages/seacas/scripts/exodus3.in.py --count --max-complexity=10 --max-line-length=79 --statistics
          flake8 packages/seacas/scripts/exomerge3.py  --count --show-source --statistics
          flake8 packages/seacas/scripts/exomerge3.py  --count --max-complexity=10 --max-line-length=79 --statistics
          flake8 packages/seacas/scripts/tests  --count --show-source --statistics
          flake8 packages/seacas/scripts/tests  --count --max-complexity=10 --max-line-length=79 --statistics
