name: Python Linting
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pylint
      - name: Lint exodus.py
        run: |
          flake8 --ignore E501,E266,E301,E302,E111,E221,E305,E261,E231,E303,W504,W503 packages/seacas/scripts/exodus3.in.py
      - name: Lint exomerge.py
        if: success() || failure()
        run: |
          flake8 --ignore E501,E266,E301,E302,E111,E221,E305,E261,E231,E303,W504,W503 packages/seacas/scripts/exomerge3.py
      - name: Lint exodus tests
        if: success() || failure()
        run: |
          flake8 --ignore E402,E501,E266,E302,E111,E221,E305,E261,E231,E303,W504,W503 packages/seacas/scripts/tests
