name: CI Formatting
on: 
  workflow_dispatch:

jobs:
  trailing:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@master
